@hostname = localhost
@port = 5101
@host = https://{{hostname}}:{{port}}
@contentType = application/json

###
GET {{host}}/api/users

###
GET {{host}}/api/users/1

###
DELETE {{host}}/api/users/1

###
POST {{host}}/api/users
Content-Type: {{contentType}}

"John Smith"

###
PUT {{host}}/api/users/0
Content-Type: {{contentType}}

"Jane Smith"