name: Build

on:
  push:
    branches: [ Assignment6 ]
  pull_request:
    branches: [ Assignment6 ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: npm
        working-directory: ./SecretSanta/src/SecretSanta.Web/
        run: |
          npm install
          npm run build:prod
      
      - name: Build
        run: dotnet build
        
      - name: directory
        run: pwd

      - name: Test
        run: dotnet test --no-build
