name: Build&Test

on:
  push:
    branches: [ Assignment* ]
  pull_request:
    branches: [ Assignment* ]

jobs:
  build:
    defaults:
      run:
        working-directory: ./SecretSanta/
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

# Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
# Install npm components and build in production 
      - name: npm
        working-directory: ./SecretSanta/src/SecretSanta.Web/
        run: |
          npm install
          npm run build:prod

# Build project
      - name: Build
        run: dotnet build
        
# Print the current working directory
      - name: Give current directory
        run: pwd

# Run all tests
      - name: Test Api and Web
        run: dotnet test --no-build
